spring:
  application:
    name: NexaCommerce

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/nexacom_db
    username: postgres
    password: firoze28

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8090
  servlet:
    context-path: /api/v1/nexa
